### ISSUE TITLE
Input type of "conv" does not allow u8 (f32 ok).

### ISSUE THREAD

**Issue by ndrean** [elixir-nx/emlx#63]
(edited for clarity)

MLX does not support integer types in matrix multiplication nor convolutions.

Seeing as Nx always expects a floating/complex output from Nx.conv, we can do upcasts beforehand.

Complex conv might need the same trick used in Torchx.Backend

**Comment by polvalente** [comment]
@ndrean thanks for the report. I've edited the issue to explain the problem and a suggested solution. Pull requests are welcome!

**Comment by ndrean** [comment]
solution is easy: `Nx.as_Type(:f32)`

**Comment by polvalente** [comment]
I suggest Nx.Type.to_floating instead, as that will avoid upcasts from f16/f8

**Comment by ndrean** [comment]
Humm, I tested `Axon.conv`, it works with the conversion.
This is ok because the coefficients are learnt.
Now if you give the coefficients and do a convolution, you need to reverse the second input, which you can't do with floats. 

What I mean is that you should probably need to provide the "real" implementation in `NxSignal.conv` instead if Nx.conv is "reserved" for Axon. I don't if I am clear.

**Comment by polvalente** [comment]
This is probably not a relevant conversation for this issue. I'm also not sure why the type would affect the ability to reverse an input.

**Comment by polvalente** [comment]
Ah, right. This is most likely just a bug in EMLX.Backend.reverse.

**Comment by polvalente** [comment]
Also, there is ongoing work on NxSignal.Convolutions :)

**Comment by ndrean** [comment]
Ok. It was because I wrongly used `Nx.Type.to_floating`. This is ok.

```
defmodule NxPoly do
  import Nx.Defn
  
  defn tprod(t1, t2) do
    t1 = Nx.stack(t1) |> Nx.as_type(:f32)
    t1 = Nx.reshape(t1, {1,1, Nx.size(t1)})
    t2 = Nx.stack(t2) |> Nx.as_type(:f32)
    t2 = Nx.reshape(t2, {1,1, Nx.size(t2)})
    
    Nx.conv(t1, Nx.reverse(t2), padding: [{2,2}])
  end
end
```
